### ISSUE TITLE
`caller.getTypeName is not a function`

### ISSUE THREAD

**Issue by ehgoodenough** [boblauer/mock-require#25]
This module is exactly what I'm looking for, but when I imported it and ran it, I got this runtime error. Any ideas what's happening here? I'm running on Node v8.

```
/workspace/node_modules/caller-id/lib/caller-id.js:12
        typeName: caller.getTypeName(),
                         ^

TypeError: caller.getTypeName is not a function
    at Object.getData (/workspace/node_modules/caller-id/lib/caller-id.js:12:26)
    at startMocking (/workspace/node_modules/mock-require/index.js:27:29)
    at Object.<anonymous> (/workspace/tests/test.js:3:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/mcphandr/.nvm/versions/node/v8.6.0/lib/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/mcphandr/.nvm/versions/node/v8.6.0/lib/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/mcphandr/.nvm/versions/node/v8.6.0/lib/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/mcphandr/.nvm/versions/node/v8.6.0/lib/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

**Comment by boblauer** [comment]
What is the exact node version? 8.0.0?

**Comment by ehgoodenough** [comment]
v8.6.0

**Comment by boblauer** [comment]
Odd, I just ran the test suite against 8.6.0 and everything passed.  Do you know if your code works in previous versions of Node?

Would you be able to put together a simple project that reproduces the error?

**Comment by ehgoodenough** [comment]
Hm, you're totally right; I can't reproduce the issue outside of my current project. I'll continue to try and hunt down what is broken about my current codebase. Thanks!

**Comment by ehgoodenough** [comment]
Could not reliably reproduce outside of our internal dependency management. Closing.
